#!/bin/bash
PHONEBOOK_ENTRIES="bash_phonebook_entries"

if [ "$#" -lt 1 ]; then
    exit 1

elif [ "$1" = "new" ]; then
    name=$2
    number=$3
    echo "$name:$phone_number" >> "$PHONEBOOK_ENTRIES"

elif [ "$1" = "list" ]; then
    if [ ! -e $PHONEBOOK_ENTRIES ] || [ ! -s $PHONEBOOK_ENTRIES ]; then
        echo "phonebook is empty"
    else
        echo "$PHONEBOOK_ENTRIES"
    fi

elif [ "$1" = "lookup" ]; then
    

elif [ "$1" = "remove" ]; then
    # YOUR CODE HERE #

elif [ "$1" = "clear" ]; then
    rm -f "$PHONEBOOK_ENTRIES"
    
else
     # YOUR CODE HERE #
fi